### PR TITLE
Integration of the development of enumerable methods of the feature branch in the develop branch.

### PR DESCRIPTION
**Pull request by aristides1000**
Integration of the development of the enumerable methods of the feature branch in the develop branch, in this project I learned the great importance of enumerable methods and how they can help us solve different problems in our daily lives as developers.

### CODE REVIEW

**Review by george-shammar — CHANGES_REQUESTED** [review]
STATUS: INVALID :red_circle: 

**Your project has linter errors.** :red_circle: 

**Friendly reminder: You should make sure that your repo looks professional before review.**

**Please take a step back and read a lesson** [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/).
**Then apply 3 simple rules from this lesson (it will be easy as you can use a template provided there)**.

**This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!**

**Review by Elbie-em — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED 🟡 

Hi @aristides1000, you have done a great job so far, congrats. However, before we have this project approved, there a couple of things to be improved.

## [GENERAL]

- [x] Rubocop flags errors when your repository is cloned, please fix this.
Screenshot 2021-04-15 at 13 55 26

## [PROJECT SPECIFIC]

- [x] *my_each*, *my_each_with_index* and *my_select* should return and **enum** if no block is given, you are returning the data set instead, please fix this.
- [x] Testing for a regex in *my_all* as params e.g *%w[ant bear cat].my_all?(/t/)* causes a compile error, please fix this.
- [x] Testing for an empty array in *my_all* should return true and not false
- [x] Testing with params in *my_any* e.g *%w[ant bear cat].my_any?(/t/)* causes a compile error, please fix this.
- [x] Testing for an empty array in *my_any* should return false, there is a compile error
- [x] Testing with params in *my_none* causes a compile error, please fix this.
- [x] *my_none, should return false if your block returns true on all elements
- [x] *my_map* should return a new array with all values within a range, there is a compile error
- [x] *longest = %w{ cat sheep bear }.inject do |memo, word|
   memo.length > word.length ? memo : word
end*
In the example above inject should be able to search for the longest word

## [OPTIONAL]

- [x] I recommend you add a file that has tests for all your methods, you can use this [link ](https://ruby-doc.org/core-3.0.0/Enumerable.html#method-i-all-3F)as a reference to create test cases

## *Kindly apply the changes requested and request another code review*

> Elbie Moonga (Part-time TSE)

> Github (@Elbie-em)
> Slack (Elbie Moonga)
> Twitter ([@ElbieEm](https://twitter.com/ElbieEm))
> LinkedIn([Elbie Moonga](https://www.linkedin.com/in/elbiemoonga/))

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @aristides1000 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

Following test cases are failing, kindly work on the suggested changes  👇.
- [x] #my_each_with_index when a block is given when self is a range returns the range itself after calling the given block once for each element in self
- [x]  #my_each_with_index when a block is given when self is a range behaves like #each_with_index calls the given block once for each element in self
- [x]  #my_each_with_index when a block is given when self is a hash behaves like #each_with_index calls the given block once for each element in self
- [x] #my_all? when a class is passed as an argument returns false if any of the collection is not a member of such class
- [x] #my_all? when a Regex is passed as an argument returns true if all of the collection matches the Regex
- [x] #my_all? when a pattern other than Regex or a Class is given returns false if any of the collection does not match the pattern
- [x] #my_any? returns false if the block ever returns a value false or nil
- [x] #my_any? when no block or argument is given returns false if at least one of the collection is not true
- [x] #my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class::Integer
- [x] #my_any? when a Regex is passed as an argument returns true if any of the collection matches the Regex
- [x] #my_any? when a pattern other than Regex or a Class is given returns false if none of the collection matches the p
- [x] #my_none? when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
- [x] #my_count returns the number of items in enum through enumeration::range
- [x] #my_map returns a new array with the results of running a given block once for every element in enum.
- [x] #my_map returns a new array with the results of running a given block once for every element in enum::range
- [x] #my_map accepts a proc as an argument and returns a new array with the results of running the proc once for every element in enum.
- [x] #my_map executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.
- [x] #my_inject raises a "LocalJumpError" when no block or argument is given
- [x] #my_inject when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method
- [x] #my_inject when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method:range
- [x] #my_inject when a symbol is specified with an initial value combines each element of the collection by applying the symbol as a named method
- [x] #my_inject when a symbol is specified with an initial value combines each element of the collection by applying the symbol as a named method::range
- [x] #multiply_els accepts an array as an argument and multiplies all the elements of the array together using #my_inject


##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by DeliceLydia — APPROVED** [review]
# Status: Approved image image

Congratulations @aristides1000 for implementing all the changes requested by the previous TSE's you nailed it! all your methods are now working perfectly.

## Feel free to merge and move on to the next adventure

All the best,

Lydia Ingabire

**Review by taiwo2 — COMMENTED** [review]
Good Job

Am really sorry for the inconvenience, I reviewed you code  and i forgot to left a comment. Am really sorry for the inconvenience it its might have caused to you.thanks for your undestanding

**Pull request merged**
